# Comprehensive NumPy Assignment

**Python for Data Science – NumPy Practice Assignment**

## Instructions
- Use only the NumPy library unless specified otherwise.
- Write clean and well-commented code.
- Display outputs for every question.
- Attempt all questions.
- Explain the logic behind your solutions wherever possible.

## Part 1: Introduction to NumPy

Q1. Import NumPy and display its version.

In [ ]:
import numpy as np
print('NumPy Version:', np.__version__)

In [ ]:
# Output: 
NumPy Version: 2.3.4

Q2. Create arrays: (1) 1-D array from 1 to 10, (2) 3x4 zeros, (3) 3x3 ones, (4) identity matrix of size 5, (5) even numbers from 2 to 20.

In [ ]:
import numpy as np
arr1=np.arange(1,11)
zeros=np.zeros((3,4))
ones=np.ones((3,3))
identity=np.eye(5)
even=np.arange(2,21,2)
print(arr1,zeros,ones,identity,even,sep='\n\n')

In [ ]:
# Output:

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[ 2  4  6  8 10 12 14 16 18 20]

Q3. Create arrays using np.arange(), np.linspace(), np.random.rand(), np.random.randint(), and np.full(). Explain the differences.

In [ ]:
import numpy as np
print(np.arange(0,10,2))
print(np.linspace(0,1,5))
print(np.random.rand(2,3))
print(np.random.randint(1,100,(2,2)))
print(np.full((2,3),7))

In [ ]:
#Output:

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.60160011 0.29422872 0.14153224]
 [0.70082393 0.40570269 0.27826366]]
[[57 99]
 [10 21]]
[[7 7 7]
 [7 7 7]]

## Array Attributes

Q4. Given arr = np.array([[10,20,30],[40,50,60],[70,80,90]]), find shape, size, dimension, dtype, itemsize, and memory occupied.

In [ ]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print('Shape',arr.shape)
print('Size',arr.size)
print('Dim',arr.ndim)
print('dtype',arr.dtype)
print('itemsize',arr.itemsize)
print('memory',arr.nbytes)

In [ ]:
#Output

Shape (3, 3)
Size 9
Dim 2
dtype int64
itemsize 8
memory 72

Q5. Convert the array into float, integer, and boolean types.

In [ ]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr.astype(float))
print(arr.astype(int))
print(arr.astype(bool))

In [ ]:
#Output

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

## Part 3: Indexing and Slicing

###### Creata a 4x4x2 array and display the elements, rows and columns

In [ ]:
import numpy as np
arr=np.arange(1,33).reshape(4,4,2)
print(arr)
print('First row:',arr[0])
print('First column:',arr[:,0,:])

In [ ]:
#Output

[21 22]
  [23 24]

 [[25 26]
  [27 28]
  [29 30]
  [31 32]]
First row: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
First column: [[ 1  2]
 [ 9 10]
 [17 18]
 [25 26]]

Q7. Reverse the entire array, rows, and columns.

In [ ]:
import numpy as np
arr=np.arange(1,17).reshape(4,4)
print(arr[::-1,::-1])
print(arr[::-1])
print(arr[:,::-1])

In [ ]:
#Output

[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]

Q8. Replace values greater than 30 with 0.

In [ ]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.where(arr>30,0,arr))

In [ ]:
#Output

[[10 20 30]
 [ 0  0  0]
 [ 0  0  0]]

## Part 4: Reshaping and Flattening

Q9. Create an array from 1 to 24 and reshape it into different dimensions. Compare flatten() and ravel().

In [ ]:
import numpy as np
arr=np.arange(1,25)
print(arr.reshape(4,6))
print(arr.reshape(2,3,4))
print(arr.flatten())
print(arr.ravel())

In [ ]:
#Output

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Q10. Demonstrate transpose(), swapaxes(), and reshape(-1).

In [ ]:
import numpy as np
arr=np.arange(1,13).reshape(3,4)
print(arr.T)
print(np.swapaxes(arr,0,1))
print(arr.reshape(-1))

In [ ]:
#Output

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]

## Part 5: Mathematical Operations

Q11. Perform arithmetic operations between arrays.

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b,a-b,a*b,a/b,sep='\n')

In [ ]:
#Output

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]

Q12. Find square root, exponential, logarithm, sine, cosine, and tangent values.

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))

In [ ]:
#Output

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]

Q13. Compare arrays using relational operators.

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,2,2])
print(a>b)
print(a==b)

In [ ]:
#Output

[False False  True]
[False  True False]

Q14. Perform Dot product of multi dimensional array

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.dot(a,b))

In [ ]:
#Output

[[19 22]
 [43 50]]

## Part 7: Aggregation Functions

Q15. Find sum, mean, median, standard deviation, variance, maximum, and minimum.

In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
print('sum',np.sum(arr))
print('mean',np.mean(arr))
print('median',np.median(arr))
print('std',np.std(arr))
print('var',np.var(arr))
print('max',np.max(arr))
print('min',np.min(arr))

In [ ]:
#Output

sum 150
mean 30.0
median 30.0
std 14.142135623730951
var 200.0
max 50
min 10

Q16. Find row-wise and column-wise statistics.

In [ ]:
import numpy as np
arr=np.arange(1,10).reshape(3,3)
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))
print(np.mean(arr,axis=0))

In [ ]:
#Output

[12 15 18]
[ 6 15 24]
[4. 5. 6.]

Q17. Find cumulative sum and cumulative product.

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(np.cumsum(arr))
print(np.cumprod(arr))

In [ ]:
#Output

[ 1  3  6 10]
[ 1  2  6 24]

## Part 8: Sorting and Searching

Q18. Sort arrays and find indices and elements satisfying conditions.

In [ ]:
import numpy as np
arr=np.array([5,2,9,1,7])
print(np.sort(arr))
print(np.argsort(arr))
print(np.where(arr>4))

In [ ]:
#Output

[1 2 5 7 9]
[3 1 0 4 2]
(array([0, 2, 4]),)

Q19. Find unique elements and their frequencies.

In [ ]:
import numpy as np
arr=np.array([1,2,2,3,3,3])
unique,counts=np.unique(arr,return_counts=True)
print(unique)
print(counts)

In [ ]:
#Output

[1 2 3]
[1 2 3]

## Part 9: Stacking and Splitting

Q20. Demonstrate stacking methods.

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

In [ ]:
#Output

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]

Q21. Split arrays into equal parts.

In [ ]:
import numpy as np
arr=np.arange(1,13)
print(np.split(arr,3))

In [ ]:
#Output

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

## Part 10: Random Module

Q22. Generate random numbers and matrices.

In [ ]:
import numpy as np
print(np.random.rand(3))
print(np.random.randint(1,10,(3,3)))

In [ ]:
#Output

[0.28068286 0.51745801 0.40941554]
[[2 3 2]
 [9 3 8]
 [9 6 3]]

Q23. Simulate rolling a die 100 times and analyze frequencies.

In [ ]:
import numpy as np
rolls=np.random.randint(1,7,100)
print(np.bincount(rolls)[1:])

In [ ]:
#Output

[16 11 13 22 18 20]

## Part 11: Boolean Masking and Filtering

Q24. Extract values based on conditions.

In [ ]:
import numpy as np
arr=np.arange(1,11)
print(arr[arr>5])

In [ ]:
#Output

[ 6  7  8  9 10]

Q25. Replace odd numbers with -1.

In [ ]:
import numpy as np
arr=np.arange(1,11)
arr[arr%2!=0]=-1
print(arr)

In [ ]:
#Output

[-1  2 -1  4 -1  6 -1  8 -1 10]

## Part 12: Missing Values

Q26. Detect and replace missing values.

In [ ]:
import numpy as np
arr=np.array([1,np.nan,3,np.nan])
print(np.isnan(arr))
arr=np.nan_to_num(arr,nan=0)
print(arr)

In [ ]:
#Output

[False  True False  True]
[1. 0. 3. 0.]

## Part 13: Linear Algebra

Q27. Perform matrix operations.

In [ ]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A+B)
print(A-B)
print(A@B)

In [ ]:
#Output

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[19 22]
 [43 50]]

Q28. Find determinant, inverse, transpose, eigenvalues, and eigenvectors.

In [ ]:
import numpy as np
A=np.array([[4,2],[1,3]])
print(np.linalg.det(A))
print(np.linalg.inv(A))
print(A.T)
vals,vecs=np.linalg.eig(A)
print(vals) ; print(vecs)

In [ ]:
#Output

10.000000000000002
[[ 0.3 -0.2]
 [-0.1  0.4]]
[[4 1]
 [2 3]]
[5. 2.]
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]

Q29. Solve a system of linear equations using NumPy.

In [ ]:
import numpy as np
A=np.array([[2,1],[1,-1]])
b=np.array([5,1])
print(np.linalg.solve(A,b))

In [ ]:
#Output
[2. 1.]

## Part 14: Advanced NumPy

Q30. Demonstrate fancy indexing, boolean indexing, where(), argmax(), argmin(), and argsort().

In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[[0,2,4]])
print(arr[arr>25])
print(np.where(arr>25,'High','Low'))
print(np.argmax(arr),np.argmin(arr),np.argsort(arr))

In [ ]:
#Output

[10 30 50]
[30 40 50]
['Low' 'Low' 'High' 'High' 'High']
4 0 [0 1 2 3 4]

Q31. Use tile(), repeat(), clip(), and diag().

In [ ]:
import numpy as np
arr=np.array([1,2,3])
print(np.tile(arr,2))
print(np.repeat(arr,2))
print(np.clip(arr,1,2))
print(np.diag([1,2,3]))

In [ ]:
#Output
[1 2 3 1 2 3]
[1 1 2 2 3 3]
[1 2 2]
[[1 0 0]
 [0 2 0]
 [0 0 3]]

Q32. Create a checkerboard pattern.

In [ ]:
import numpy as np
board=np.zeros((8,8),dtype=int)
board[1::2,::2]=1
board[::2,1::2]=1
print(board)

In [ ]:
#Output
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

Q33. Write a line of code to extract the inner 2×2 submatrix (excluding the border rows and columns).

In [ ]:
import numpy as np
arr=np.arange(1,17).reshape(4,4)
print(arr[1:3,1:3])

In [ ]:
#Output
[[ 6  7]
 [10 11]]

Q34. Reshape a 1D array of 12 elements (from Step 4) into a 3×4 2D matrix.

In [ ]:
import numpy as np
arr=np.arange(1,13)
print(arr.reshape(3,4))

In [ ]:
#Output
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Q35 Create a 3×3 identity matrix.

In [ ]:
import numpy as np
print(np.eye(3))

In [ ]:
#Output
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Q35. Stack two identical 2×2 arrays of ones vertically.

In [ ]:
import numpy as np
a=np.ones((2,2))
print(np.vstack((a,a)))

In [ ]:
#Output
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Q36. Create Matrix A with dimensions 2×3 and Matrix B with dimensions 3×2.

In [ ]:
import numpy as np
A=np.arange(1,7).reshape(2,3)
B=np.arange(1,7).reshape(3,2)
print(A)
print(B)

In [ ]:
#Output
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]

Q37. Perform a matrix multiplication (A × B) to yield a 2×2 matrix result.

In [ ]:
import numpy as np
A=np.arange(1,7).reshape(2,3)
B=np.arange(1,7).reshape(3,2)
print(A@B)

In [ ]:
#Output
[[22 28]
 [49 64]]

# Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [ ]:
import numpy as np

x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.zeros(x.shape)
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        y[i,j] = x[i,j] + v[j]

print(y)

In [ ]:
#Output
[[11 21 31]
 [12 22 32]
 [13 23 33]]